# Generated by Django 2.1.7 on 2019-03-02 13:41

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0003_auto_20190227_2153'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Quantity')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_orders', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_orders', to='goods.Good', verbose_name='Good')),
            ],
            options={
                'verbose_name': 'Good order',
                'verbose_name_plural': 'Good orders',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('sent', 'Sent'), ('completed', 'Completed')], default='new', max_length=20, verbose_name='Status')),
                ('delivery_city', models.CharField(max_length=50, verbose_name='Delivery city')),
                ('delivery_method', models.CharField(choices=[('pickup', 'Pickup'), ('new_post_branch', 'New post branch'), ('new_post_express', 'New post express')], max_length=30, verbose_name='Delivery method')),
                ('delivery_info', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Delivery info')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='goodorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good_orders', to='orders.Order', verbose_name='Order'),
        ),
    ]
