# Generated by Django 2.1.5 on 2019-02-07 14:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import djmoney.models.validators
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=30, null=True, verbose_name='Name')),
                ('name_uk', models.CharField(max_length=30, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=30, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('description_uk', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('UAH', 'Hryvnia')], default='UAH', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='UAH', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Good',
                'verbose_name_plural': 'Goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=30, null=True, verbose_name='Name')),
                ('name_uk', models.CharField(max_length=30, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=30, null=True, verbose_name='Name')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='goods.GoodsCategory', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'goods category',
                'verbose_name_plural': 'goods categories',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='goods.GoodsCategory', verbose_name='Category'),
        ),
    ]
