# Generated by Django 2.1.5 on 2019-02-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='stores.Store', verbose_name='Seller'),
        ),
        migrations.AlterUniqueTogether(
            name='goodscategory',
            unique_together={('name', 'parent_category')},
        ),
        migrations.AlterUniqueTogether(
            name='good',
            unique_together={('name', 'category')},
        ),
    ]
