# Generated by Django 2.1.7 on 2019-02-27 19:53

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_color_size'),
        ('goods', '0002_auto_20190207_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodSpecifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Color', verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Good specifications',
                'verbose_name_plural': 'Good specifications',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='applicable_specifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None, verbose_name='Applicable specifications'),
        ),
        migrations.AddField(
            model_name='goodspecifications',
            name='good',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_specifications', to='goods.Good', verbose_name='Good'),
        ),
        migrations.AddField(
            model_name='goodspecifications',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Size', verbose_name='Size'),
        ),
    ]
