# Generated by Django 2.1.7 on 2019-03-03 18:47

from django.db import migrations


def add_categories(apps, schema_editor):
    GoodsCategory = apps.get_model('goods', 'GoodsCategory')
    categories = [
        {
            'name': 'Clothes',
            'name_en': 'Clothes',
            'name_uk': 'Одяг',
            'name_ru': 'Одежда',
        },
        {
            'name': 'Jewelry',
            'name_en': 'Jewelry',
            'name_uk': 'Прикраси',
            'name_ru': 'Украшения',
        },
        {
            'name': 'Accessories',
            'name_en': 'Accessories',
            'name_uk': 'Аксесуари',
            'name_ru': 'Аксессуары',
        },
        {
            'name': 'Home decor',
            'name_en': 'Home decor',
            'name_uk': 'Домашній декор',
            'name_ru': 'Домашний декор',
        },
        {
            'name': 'Shoes',
            'name_en': 'Shoes',
            'name_uk': 'Взуття',
            'name_ru': 'Обувь',
        },
        {
            'name': 'Art',
            'name_en': 'Art',
            'name_uk': 'Мистецтво',
            'name_ru': 'Искусство',
        },
        {
            'name': 'Other',
            'name_en': 'Other',
            'name_uk': 'Інше',
            'name_ru': 'Другое',
        },
    ]
    for category in categories:
        GoodsCategory.objects.get_or_create(name=category.pop('name'), defaults=category)


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190227_2153'),
    ]

    operations = [
        migrations.RunPython(add_categories, reverse_code=migrations.RunPython.noop)
    ]
