# Generated by Django 2.0.2 on 2018-08-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_good'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='good',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='goodscategory',
            unique_together={('name', 'parent_category')},
        ),
    ]
