# Generated by Django 2.1.7 on 2019-03-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190303_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscategory',
            name='slug',
            field=models.SlugField(default=' ', max_length=30, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
