# Generated by Django 2.0.2 on 2018-09-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_good_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='description_ru',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='description_uk',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='name_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='name_uk',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='name_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='name_uk',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
