# Generated by Django 2.1.7 on 2019-03-04 18:37

from django.db import migrations


def add_categories_slug(apps, schema_editor):
    GoodsCategory = apps.get_model('goods', 'GoodsCategory')
    for category in GoodsCategory.objects.all():
        category.slug = category.name_en.lower().replace(' ', '_')
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_goodscategory_slug'),
    ]

    operations = [
        migrations.RunPython(add_categories_slug, reverse_code=migrations.RunPython.noop)
    ]
