# Generated by Django 2.1.7 on 2019-03-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20190304_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='Slug'),
        ),
    ]
