# Generated by Django 2.1.7 on 2019-03-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20190304_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_in_stock',
            field=models.BooleanField(default=True, verbose_name='In stock'),
        ),
    ]
