# Generated by Django 2.0.2 on 2018-09-16 04:55

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20180915_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='UAH', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
    ]
