# Generated by Django 2.1.7 on 2019-03-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_good_is_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Image URL')),
            ],
        ),
        migrations.RemoveField(
            model_name='good',
            name='is_in_stock',
        ),
        migrations.AddField(
            model_name='good',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not available'), ('on_request', 'On request')], default='available', max_length=20, verbose_name='Availability'),
        ),
        migrations.AddField(
            model_name='goodimage',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.Good', verbose_name='Good image'),
        ),
    ]
