# Generated by Django 2.1.7 on 2019-03-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20190310_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is main'),
        ),
    ]
