# Generated by Django 2.1.5 on 2019-02-07 07:43
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CITextExtension()
    ]
