# Generated by Django 2.1.7 on 2019-02-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=30, verbose_name='Definition')),
                ('definition_ru', models.CharField(max_length=30, null=True, verbose_name='Definition')),
                ('definition_uk', models.CharField(max_length=30, null=True, verbose_name='Definition')),
                ('definition_en', models.CharField(max_length=30, null=True, verbose_name='Definition')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=30, verbose_name='Definition')),
                ('definition_ru', models.CharField(max_length=30, null=True, verbose_name='Definition')),
                ('definition_uk', models.CharField(max_length=30, null=True, verbose_name='Definition')),
                ('definition_en', models.CharField(max_length=30, null=True, verbose_name='Definition')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
    ]
