# Generated by Django 2.1.5 on 2019-02-07 14:16

import common.fields
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        # ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoloUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'That username is already taken.'}, max_length=30, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, default='', max_length=30, verbose_name='First name')),
                ('first_name_ru', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='First name')),
                ('first_name_uk', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='First name')),
                ('first_name_en', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, default='', max_length=30, verbose_name='Last name')),
                ('last_name_ru', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Last name')),
                ('last_name_uk', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Last name')),
                ('last_name_en', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Last name')),
                ('email', django.contrib.postgres.fields.citext.CIEmailField(error_messages={'unique': 'That email address is already taken.'}, max_length=254, unique=True, verbose_name='Email')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Email confirmed')),
                ('email_confirm_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('phone', common.fields.PhoneField(blank=True, error_messages={'unique': 'That phone number is already taken.'}, max_length=15, null=True, unique=True, verbose_name='Phone')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.avatar_upload_path, verbose_name='Avatar')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', django.contrib.postgres.fields.citext.CIEmailField(error_messages={'unique': 'That email address is already subscribed.'}, max_length=254, unique=True, verbose_name='Email')),
                ('subscribed', models.BooleanField(default=True, verbose_name='Subscribed')),
                ('edit_token', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
