# Generated by Django 2.0.2 on 2018-02-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_holouser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holouser',
            name='username',
            field=models.CharField(error_messages={'unique': 'That username is already taken.'}, max_length=30, unique=True),
        ),
    ]
