# Generated by Django 2.0.2 on 2018-02-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180211_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
