# Generated by Django 2.0.2 on 2018-02-13 21:35
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_subscription_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='edit_token',
            field=models.UUIDField(default=uuid.uuid4),
            preserve_default=False,
        ),
    ]
