# Generated by Django 2.0.2 on 2018-02-17 12:22

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180213_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='holouser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.avatar_upload_path),
        ),
    ]
