# Generated by Django 2.0.2 on 2018-02-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_holouser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holouser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='holouser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
