# Generated by Django 2.0.2 on 2018-02-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180217_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holouser',
            name='first_name',
            field=models.CharField(default='HoloUser', max_length=30),
        ),
    ]
