# Generated by Django 2.0.2 on 2018-02-18 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180218_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='holouser',
            name='email_confirm_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='holouser',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
