# Generated by Django 2.0.2 on 2018-02-21 17:21

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180218_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holouser',
            name='phone',
            field=common.fields.PhoneField(blank=True, default='', error_messages={'unique': 'That phone number is already taken.'}, max_length=15, unique=True),
        ),
    ]
