# Generated by Django 2.0.2 on 2018-02-22 19:16

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180221_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holouser',
            name='phone',
            field=common.fields.PhoneField(blank=True, error_messages={'unique': 'That phone number is already taken.'}, max_length=15, null=True, unique=True),
        ),
    ]
