# Generated by Django 2.0.2 on 2018-09-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180222_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='holouser',
            name='first_name_en',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='holouser',
            name='first_name_ru',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='holouser',
            name='first_name_uk',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='holouser',
            name='last_name_en',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='holouser',
            name='last_name_ru',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='holouser',
            name='last_name_uk',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
