# Generated by Django 2.1.3 on 2018-11-25 10:37

import common.fields
from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180908_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holouser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterField(
            model_name='holouser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.avatar_upload_path, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='holouser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined'),
        ),
        migrations.AlterField(
            model_name='holouser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'That email address is already taken.'}, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='holouser',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email confirmed'),
        ),
        migrations.AlterField(
            model_name='holouser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='holouser',
            name='first_name_en',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='holouser',
            name='first_name_ru',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='holouser',
            name='first_name_uk',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='holouser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='holouser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff status'),
        ),
        migrations.AlterField(
            model_name='holouser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='holouser',
            name='last_name_en',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='holouser',
            name='last_name_ru',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='holouser',
            name='last_name_uk',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='holouser',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='holouser',
            name='phone',
            field=common.fields.PhoneField(blank=True, error_messages={'unique': 'That phone number is already taken.'}, max_length=15, null=True, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(error_messages={'unique': 'That email address is already subscribed.'}, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscribed',
            field=models.BooleanField(default=True, verbose_name='Subscribed'),
        ),
    ]
