# Generated by Django 2.1.3 on 2018-11-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20181125_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holouser',
            name='username',
            field=models.CharField(error_messages={'unique': 'That username is already taken.'}, max_length=30, unique=True, verbose_name='Username'),
        ),
    ]
