# Generated by Django 2.1.5 on 2019-02-07 07:49

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0018_auto_20181125_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holouser',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(error_messages={'unique': 'That email address is already taken.'}, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(error_messages={'unique': 'That email address is already subscribed.'}, max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
