# Generated by Django 2.1.5 on 2019-02-07 14:16

import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import stores.models.store_application_image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('store_name', models.CharField(max_length=30, unique=True, verbose_name='Store name')),
                ('store_name_ru', models.CharField(max_length=30, null=True, unique=True, verbose_name='Store name')),
                ('store_name_uk', models.CharField(max_length=30, null=True, unique=True, verbose_name='Store name')),
                ('store_name_en', models.CharField(max_length=30, null=True, unique=True, verbose_name='Store name')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='StoreApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='What is your name?', max_length=61, verbose_name='Name')),
                ('email', django.contrib.postgres.fields.citext.CIEmailField(error_messages={'unique': 'That email address is already used.'}, help_text='Email to reach you out', max_length=254, unique=True, verbose_name='Email')),
                ('instagram_name', models.CharField(error_messages={'unique': 'That Instagram name is already used.'}, help_text='@Name in Instagram', max_length=254, unique=True, verbose_name='Instagram name')),
                ('category', models.CharField(choices=[('', 'Category'), ('clothes', 'Clothes'), ('jewelry', 'Jewelry'), ('accessories', 'Accessories'), ('home_decor', 'Home decor'), ('shoes', 'Shoes'), ('art', 'Art'), ('other', 'Other')], max_length=30, verbose_name='Category')),
                ('selling_goods', models.TextField(help_text="What's being sold in your store?", max_length=500, verbose_name='Selling goods')),
                ('goods_description', models.TextField(help_text='Describe your goods (materials, technology, prices...)', max_length=1000, validators=[django.core.validators.MinLengthValidator(100)], verbose_name='Goods description')),
                ('philosophy', models.TextField(help_text='Philosophy behind your store', max_length=1000, validators=[django.core.validators.MinLengthValidator(100)], verbose_name='Philosophy')),
                ('data_usage_agreement', models.BooleanField(default=False, help_text='I allow usage of data I provided', verbose_name='Data usage agreement')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='Publication date')),
            ],
            options={
                'verbose_name': 'Store application',
                'verbose_name_plural': 'Store applications',
            },
        ),
        migrations.CreateModel(
            name='StoreApplicationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=stores.models.store_application_image.upload_path, verbose_name='Image')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stores.StoreApplication', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Store application image',
                'verbose_name_plural': 'Store application images',
            },
        ),
    ]
