# Generated by Django 2.0.2 on 2018-08-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_name',
            field=models.CharField(default='Admin store', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
