# Generated by Django 2.0.2 on 2018-09-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_name_en',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_ru',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_uk',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
