# Generated by Django 2.1.7 on 2019-02-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeapplicationimage',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
