# Generated by Django 2.1.3 on 2018-11-10 12:09

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20180908_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=61, verbose_name='Name')),
                ('email', models.EmailField(error_messages={'unique': 'That email address is already used.'}, max_length=254, unique=True, verbose_name='Email')),
                ('instagram_name', models.CharField(error_messages={'unique': 'That Instagram name is already used.'}, max_length=254, unique=True, verbose_name='Instagram name')),
                ('category', models.CharField(choices=[('clothes', 'Clothes'), ('jewelry', 'Jewelry'), ('accessories', 'Accessories'), ('home_decor', 'Home decor'), ('shoes', 'Shoes')], max_length=30, verbose_name='Category')),
                ('selling_goods', models.TextField(max_length=500, verbose_name='Selling goods')),
                ('goods_description', models.TextField(max_length=500, verbose_name='Goods description')),
                ('philosophy', models.TextField(max_length=500, verbose_name='Philosophy')),
                ('data_usage_agreement', models.BooleanField(default=False, verbose_name='Data usage agreement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
