# Generated by Django 2.1.3 on 2018-11-10 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_storeapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeapplication',
            name='goods_description',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(500)], verbose_name='Goods description'),
        ),
        migrations.AlterField(
            model_name='storeapplication',
            name='philosophy',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(500)], verbose_name='Philosophy'),
        ),
    ]
