# Generated by Django 2.1.3 on 2018-11-10 12:54

from django.db import migrations, models
import django.db.models.deletion
import stores.models.store_application_image


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20181110_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreApplicationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=stores.models.store_application_image.upload_path)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stores.StoreApplication')),
            ],
        ),
    ]
