# Generated by Django 2.1.7 on 2019-02-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_remove_storeapplicationimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeapplicationimage',
            name='image_url',
            field=models.URLField(verbose_name='Image URL'),
        ),
    ]
