# Generated by Django 2.1.3 on 2018-11-11 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_storeapplicationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeapplication',
            name='data_usage_agreement',
            field=models.BooleanField(default=False, help_text='I allow usage of data I provided', verbose_name='Data usage agreement'),
        ),
        migrations.AlterField(
            model_name='storeapplication',
            name='email',
            field=models.EmailField(error_messages={'unique': 'That email address is already used.'}, help_text='Email to reach you out', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='storeapplication',
            name='goods_description',
            field=models.TextField(help_text='Describe your goods (materials, technology, prices...)', max_length=1000, validators=[django.core.validators.MinLengthValidator(500)], verbose_name='Goods description'),
        ),
        migrations.AlterField(
            model_name='storeapplication',
            name='instagram_name',
            field=models.CharField(error_messages={'unique': 'That Instagram name is already used.'}, help_text='@Name in Instagram', max_length=254, unique=True, verbose_name='Instagram name'),
        ),
        migrations.AlterField(
            model_name='storeapplication',
            name='name',
            field=models.CharField(help_text='What is your name?', max_length=61, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='storeapplication',
            name='philosophy',
            field=models.TextField(help_text='Philosophy behind your store', max_length=1000, validators=[django.core.validators.MinLengthValidator(500)], verbose_name='Philosophy'),
        ),
        migrations.AlterField(
            model_name='storeapplication',
            name='selling_goods',
            field=models.TextField(help_text="What's being sold in your store?", max_length=500, verbose_name='Selling goods'),
        ),
    ]
