# Generated by Django 2.1.7 on 2019-02-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_auto_20190223_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='location_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='location_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='location_uk',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
