# Generated by Django 2.1.3 on 2018-11-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_auto_20181111_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeapplication',
            name='pub_date',
            field=models.DateField(null=True, blank=True, verbose_name='Publication date'),
        ),
    ]
