# Generated by Django 2.1.7 on 2019-03-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_auto_20190223_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Store name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Store name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_ru',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Store name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_uk',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Store name'),
        ),
    ]
