# Generated by Django 2.1.3 on 2018-11-11 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stores.models.store_application_image


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_auto_20181111_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.AlterModelOptions(
            name='storeapplication',
            options={'verbose_name': 'Store application', 'verbose_name_plural': 'Store applications'},
        ),
        migrations.AlterModelOptions(
            name='storeapplicationimage',
            options={'verbose_name': 'Store application image', 'verbose_name_plural': 'Store application images'},
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Store name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_en',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Store name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_ru',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Store name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_uk',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Store name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_store', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='storeapplicationimage',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stores.StoreApplication', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='storeapplicationimage',
            name='image',
            field=models.ImageField(upload_to=stores.models.store_application_image.upload_path, verbose_name='Image'),
        ),
    ]
