# Generated by Django 2.1.3 on 2018-11-20 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_auto_20181111_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeapplication',
            name='goods_description',
            field=models.TextField(help_text='Describe your goods (materials, technology, prices...)', max_length=1000, validators=[django.core.validators.MinLengthValidator(100)], verbose_name='Goods description'),
        ),
        migrations.AlterField(
            model_name='storeapplication',
            name='philosophy',
            field=models.TextField(help_text='Philosophy behind your store', max_length=1000, validators=[django.core.validators.MinLengthValidator(100)], verbose_name='Philosophy'),
        ),
    ]
