# Generated by Django 2.1.5 on 2019-01-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_auto_20181120_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeapplication',
            name='category',
            field=models.CharField(choices=[('', 'Category'), ('clothes', 'Clothes'), ('jewelry', 'Jewelry'), ('accessories', 'Accessories'), ('home_decor', 'Home decor'), ('shoes', 'Shoes'), ('art', 'Art'), ('other', 'Other')], max_length=30, verbose_name='Category'),
        ),
    ]
