# Generated by Django 2.1.5 on 2019-02-07 07:49

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('stores', '0013_auto_20190130_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeapplication',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(error_messages={'unique': 'That email address is already used.'}, help_text='Email to reach you out', max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
